import { z } from 'zod';
import {registryEntrySchema} from './registry';
import { approvedFact, evaluateApproval, factBlockers, factRequirementSchema, findingSchema, unresolvedFindings } from './approval';
import type { ApprovalBlocker, FactRequirement } from './approval';
import { factEvidence, factSchema, idSchema, reviewStatusSchema, sha256Schema } from './evidence';
import type { SourceEvidence } from './evidence';
import { ruleEvidence, ruleSchema } from './rule-schema';
import { canonicalJson, contentHash } from './canonical';

const pageRefSchema = z.strictObject({ documentId: idSchema, pageNumber: z.number().int().positive() });
const auditSchema = z.strictObject({ actorId: idSchema, at: z.iso.datetime(), reason: idSchema });
const categorySchema = z.enum(['wall_cabinet', 'base_cabinet', 'tall_cabinet', 'vanity', 'corner_cabinet', 'oven_cabinet', 'refrigerator_cabinet', 'pantry', 'panel', 'filler', 'molding', 'accessory', 'hardware', 'other']);
export const productSchema = z.strictObject({
  id: idSchema, reviewStatus: reviewStatusSchema,
  fields: z.record(idSchema, factSchema),
});
const receiptSchema = z.strictObject({
  runId: idSchema, candidateRevision: z.number().int().nonnegative(),
  contentHash: sha256Schema, passed: z.boolean(),
});
export const candidateSchema = z.strictObject({
  id: idSchema, revision: z.number().int().nonnegative(), status: z.enum(['draft', 'review', 'published']),
  seriesId: idSchema,
  compilerVersion: idSchema, schemaVersion: idSchema, promptVersion: idSchema, modelVersion: idSchema,
  documents: z.array(z.strictObject({ id: idSchema, sha256: sha256Schema, pageCount: z.number().int().positive() })).min(1),
  coverage: z.discriminatedUnion('kind', [
    z.strictObject({ kind: z.literal('full_document') }),
    z.strictObject({ kind: z.literal('subset'), label: idSchema, pages: z.array(pageRefSchema).min(1) }),
  ]),
  pages: z.array(z.strictObject({
    ...pageRefSchema.shape,
    status: z.enum(['pending', 'processed', 'failed', 'ignored']),
    contentType: z.enum(['catalog', 'non_catalog', 'unknown']),
    ignoreAudit: auditSchema.optional(),
  })),
  registries:z.array(registryEntrySchema).default([]),
  products: z.array(productSchema), rules: z.array(ruleSchema), findings: z.array(findingSchema),
  // Category policies are server-owned configuration, never generated by the extractor.
  additionalCategoryProfiles: z.array(z.strictObject({
    category: categorySchema, version: idSchema, audit: auditSchema,
    requirements: z.record(idSchema, factRequirementSchema),
  })),
  benchmark: z.strictObject({
    ...receiptSchema.shape, fixtureRevision: idSchema, scope: z.enum(['milestone_1', 'full_document']),
    truthStatus: z.enum(['draft', 'human_verified']),
    productsPass: z.boolean(), fieldsPass: z.boolean(), rulesPass: z.boolean(), footnotesPass: z.boolean(),
  }).optional(),
  validation: receiptSchema.optional(),
});
export type CatalogCandidate = z.infer<typeof candidateSchema>;
export type GateIssue = { code: string; entityId?: string; detail: string };
export type PublicationGate = { candidateId: string; revision: number; contentHash: string; receiptHash: string; publishable: boolean; issues: GateIssue[] };
const numberRequired: FactRequirement = { required: true, valueType: 'number', positiveDimension: true };
const stringRequired: FactRequirement = { required: true, valueType: 'string', positiveDimension: false };
const cabinetCategories = new Set(['wall_cabinet', 'base_cabinet', 'tall_cabinet', 'vanity', 'corner_cabinet', 'oven_cabinet', 'refrigerator_cabinet', 'pantry']);
function pageKey(p: { documentId: string; pageNumber: number }): string { return `${p.documentId}:${p.pageNumber}`; }
export function candidateContentHash(candidate: CatalogCandidate): string {
  // Receipts certify the content; including them in their own subject hash would be circular.
  const { benchmark: _benchmark, validation: _validation, ...content } = candidate;
  void _benchmark; void _validation;
  return contentHash(content);
}
function receiptHash(candidate: CatalogCandidate): string {
  return contentHash({ benchmark: candidate.benchmark ?? null, validation: candidate.validation ?? null });
}
export function evaluatePublication(raw: unknown): PublicationGate {
  const candidate = candidateSchema.parse(raw);
  const hash = candidateContentHash(candidate), issues: GateIssue[] = [];
  const issue = (code: string, detail: string, entityId?: string) => issues.push({ code, detail, ...(entityId === undefined ? {} : { entityId }) });
  if (candidate.status === 'published') issue('immutable_version', 'Published versions cannot be republished or edited');
  if (!candidate.products.length) issue('empty_catalog', 'A catalog must contain products');
  const unique = (ids: string[], type: string) => {
    const seen = new Set<string>();
    for (const id of ids) { if (seen.has(id)) issue('duplicate_identity', `Duplicate ${type}: ${id}`); seen.add(id); }
  };
  unique(candidate.documents.map(d => d.id), 'document'); unique(candidate.products.map(p => p.id), 'product');
  unique(candidate.rules.map(r => r.id), 'rule'); unique(candidate.findings.map(f => f.id), 'finding');
  unique(candidate.additionalCategoryProfiles.map(p => p.category), 'category profile');
  const documents = new Map(candidate.documents.map(d => [d.id, d]));
  const expected = candidate.coverage.kind === 'subset' ? candidate.coverage.pages : candidate.documents.flatMap(d => Array.from({ length: d.pageCount }, (_, i) => ({ documentId: d.id, pageNumber: i + 1 })));
  unique(expected.map(pageKey), 'coverage page'); unique(candidate.pages.map(pageKey), 'page');
  const expectedKeys = new Set(expected.map(pageKey));
  const pages = new Map(candidate.pages.map(p => [pageKey(p), p]));
  for (const p of expected) {
    const document = documents.get(p.documentId);
    if (!document || p.pageNumber > document.pageCount) issue('invalid_coverage', `Page ${pageKey(p)} is outside a source document`);
    const page = pages.get(pageKey(p));
    if (!page) { issue('page_not_processed', `Missing page ${pageKey(p)}`); continue; }
    if (page.status === 'ignored') {
      if (page.contentType !== 'non_catalog' || !page.ignoreAudit) issue('invalid_page_ignore', `Page ${pageKey(p)} cannot be ignored without non-catalog classification and audit`);
    } else if (page.status !== 'processed') issue('page_not_processed', `Page ${pageKey(p)} is ${page.status}`);
    else if (page.contentType === 'unknown') issue('page_classification_required', `Page ${pageKey(p)} has unknown content type`);
  }
  for (const p of candidate.pages) {
    if (!expectedKeys.has(pageKey(p))) issue('undeclared_page', `Page ${pageKey(p)} is outside declared coverage`);
  }
  const evidenceById = new Map<string, string>();
  function checkEvidence(evidence: SourceEvidence[], entityId: string) {
    for (const e of evidence) {
      const serialized = canonicalJson(e), prior = evidenceById.get(e.id);
      if (prior && prior !== serialized) issue('conflicting_evidence_identity', `Evidence ID ${e.id} identifies different source regions`, entityId);
      evidenceById.set(e.id, serialized);
      const document = documents.get(e.documentId);
      if (!document || e.documentSha256 !== document.sha256 || e.pageNumber > document.pageCount) issue('invalid_provenance', `Invalid source reference ${e.id}`, entityId);
      if (!expectedKeys.has(pageKey(e))) issue('missing_dependency_page', `Evidence ${e.id} is outside declared coverage`, entityId);
      if (pages.get(pageKey(e))?.status !== 'processed') issue('unprocessed_evidence', `Evidence ${e.id} is not on a processed page`, entityId);
    }
  }
  const unresolved = unresolvedFindings(candidate.findings, candidate.revision);
  for (const finding of candidate.findings) {
    if (finding.resolution && finding.resolution.candidateRevision === candidate.revision && finding.resolution.validationRunId !== candidate.validation?.runId) {
      issue('uncertified_resolution', `Finding ${finding.id} resolution is not tied to the current validation run`, finding.entityId);
    }
  }
  for (const f of unresolved) {
    if (f.severity === 'blocking') issue(f.code, `Unresolved finding ${f.id}`, f.entityId);
  }
  const blockersFor = (entityId: string): ApprovalBlocker[] => unresolved.filter(f => f.entityId === entityId).map(f => f.code);
  const facts = new Map<string, z.infer<typeof factSchema>>();
  const skuProducts = new Map<string, string>();
  for (const product of candidate.products) {
    if (product.reviewStatus === 'rejected') { issue('rejected_record_in_snapshot', 'Remove rejected records from the publication snapshot and recertify coverage', product.id); continue; }
    if (product.reviewStatus === 'unreviewed') issue('review_required', 'Product has not been reviewed', product.id);
    const categoryFact = product.fields.normalizedCategory;
    const category = categoryFact?.state === 'known' ? categoryFact.value : undefined;
    const requirements: Record<string, FactRequirement> = { sku: stringRequired, normalizedCategory: stringRequired };
    if (typeof category !== 'string' || !categorySchema.safeParse(category).success) issue('missing_required_field', 'A recognized category is required', product.id);
    else if (cabinetCategories.has(category)) {
      for (const field of ['widthIn', 'heightIn', 'depthIn']) requirements[field] = numberRequired;
    } else if (category === 'panel' || category === 'filler') {
      for (const field of ['widthIn', 'heightIn', 'thicknessIn']) requirements[field] = numberRequired;
    } else if (category === 'molding') {
      for (const field of ['lengthIn', 'profileWidthIn', 'profileHeightIn']) requirements[field] = numberRequired;
    } else if (!candidate.additionalCategoryProfiles.some(p => p.category === category)) {
      issue('category_profile_required', `Define an audited dimension profile for ${category}`, product.id);
    }
    const profile = candidate.additionalCategoryProfiles.find(p => p.category === category);
    if (profile) {
      for (const [key, value] of Object.entries(profile.requirements)) {
        const mandatory = requirements[key];
        if (mandatory && (value.valueType !== mandatory.valueType || !value.required || (mandatory.positiveDimension && !value.positiveDimension))) {
          issue('invalid_category_profile', `Profile cannot weaken mandatory field ${key}`, product.id);
        } else requirements[key] = value;
      }
      if (!Object.values(profile.requirements).some(r => r.required && r.valueType === 'number')) issue('invalid_category_profile', 'Additional profile must establish required numeric geometry', product.id);
    }
    for (const [key, requirement] of Object.entries(requirements)) {
      for (const code of factBlockers(product.fields[key], requirement)) issue(code, `Invalid required field ${key}`, product.id);
    }
    const productBlockers = blockersFor(product.id);
    for (const [key, fact] of Object.entries(product.fields)) {
      if (facts.has(fact.id)) issue('duplicate_identity', `Duplicate fact ID ${fact.id}`, product.id);
      facts.set(fact.id, fact);
      checkEvidence(factEvidence(fact), product.id);
      const requirement = requirements[key] ?? { required: false, valueType: fact.state === 'known' ? typeof fact.value as 'string' | 'number' | 'boolean' : 'string', positiveDimension: false };
      const blockers = [...productBlockers, ...blockersFor(fact.id), ...factBlockers(fact, requirement)];
      for (const code of factBlockers(fact, requirement)) issue(code, `Invalid field ${key}`, product.id);
      if (fact.state === 'unknown' || fact.state === 'conflict') issue('unresolved_field', `Resolve or explicitly omit field ${key}`, product.id);
      if (!approvedFact(fact)) issue('review_required', `Field ${key} is not approved`, product.id);
      if (fact.reviewStatus === 'auto_approved' && !evaluateApproval({ confidence: fact.confidence, blockers, reviewStatus: fact.reviewStatus }).eligibleForAutoApproval) issue('ineligible_auto_approval', `Field ${key} is not eligible`, product.id);
      if (product.reviewStatus === 'auto_approved' && (!evaluateApproval({ confidence: fact.confidence, blockers, reviewStatus: fact.reviewStatus }).eligibleForAutoApproval || !approvedFact(fact))) issue('ineligible_auto_approval', `Product depends on ineligible field ${key}`, product.id);
    }
    const sku = product.fields.sku;
    if (sku?.state === 'known' && typeof sku.value === 'string') {
      if (skuProducts.has(sku.value)) issue('duplicate_sku_conflict', `SKU ${sku.value} appears more than once`, product.id);
      skuProducts.set(sku.value, product.id);
    }
  }
  // Resolve the complete derivation graph, including cycles across multiple fields.
  const visiting = new Set<string>(), visited = new Set<string>();
  function visit(id: string) {
    if (visiting.has(id)) { issue('invalid_derivation', `Derivation cycle at ${id}`); return; }
    if (visited.has(id)) return;
    const fact = facts.get(id);
    if (!fact) { issue('invalid_derivation', `Missing derivation input ${id}`); return; }
    visiting.add(id);
    for (const input of fact.derivation?.inputFactIds ?? []) {
      const inputFact = facts.get(input);
      if (inputFact && (inputFact.state !== 'known' || !approvedFact(inputFact))) issue('invalid_derivation', `Unresolved derivation input ${input}`, id);
      visit(input);
    }
    visiting.delete(id); visited.add(id);
  }
  for (const id of facts.keys()) visit(id);
  const productIds = new Set(candidate.products.map(p => p.id));
  for (const rule of candidate.rules) {
    checkEvidence(ruleEvidence(rule), rule.id);
    if (rule.catalogVersionId !== candidate.id) issue('rule_version_mismatch', 'Rule belongs to a different catalog version', rule.id);
    if (rule.scope.kind === 'products' && rule.scope.targets.some(t => !productIds.has(t.value))) issue('dangling_rule_scope', 'Rule references a missing product', rule.id);
    if (rule.scope.kind === 'series' && rule.scope.targets.some(t => t.value !== candidate.seriesId)) issue('dangling_rule_scope', 'Rule references a different series', rule.id);
    if (rule.scope.kind === 'categories' && rule.scope.targets.some(t => !categorySchema.safeParse(t.value).success)) issue('dangling_rule_scope', 'Rule references an unknown category', rule.id);
    if (rule.modelingStatus === 'modeled') {
      const constraint = rule.constraint;
      if('target' in constraint&&['option','modification'].includes(constraint.target.kind)&&!candidate.registries.some(r=>r.entityKind===constraint.target.kind&&r.id===constraint.target.id.value))issue('dangling_rule_target','Rule target is absent from the option/modification registry',rule.id);
      if('modificationId' in constraint&&!candidate.registries.some(r=>r.entityKind==='modification'&&r.id===constraint.modificationId.value))issue('dangling_rule_target','Modification is absent from the registry',rule.id);
      if ((constraint.type === 'requires' || constraint.type === 'excludes' || constraint.type === 'conditional_requirement') && constraint.target.kind === 'product' && !productIds.has(constraint.target.id.value)) issue('dangling_rule_target', 'Rule references a product missing from the snapshot', rule.id);
      if ((constraint.type === 'allowed_values' || constraint.type === 'forbidden_values') && constraint.field === 'hostSku' && constraint.values.some(v => !skuProducts.has(v.value))) issue('dangling_rule_target', 'Host SKU is not present in the snapshot', rule.id);
    }
    if (rule.scope.kind === 'families'&&rule.scope.targets.some(t=>!candidate.registries.some(r=>r.entityKind==='family'&&r.id===t.value))) issue('unresolved_family_scope', 'Family scope must reference a catalog family', rule.id);
    if(rule.scope.kind==='modifications'&&rule.scope.targets.some(t=>!candidate.registries.some(r=>r.entityKind==='modification'&&r.id===t.value)))issue('unresolved_modification_scope','Modification scope must reference a catalog modification',rule.id);
    if (rule.reviewStatus === 'unreviewed' || rule.reviewStatus === 'rejected') issue('review_required', 'Rule is not approved', rule.id);
    const blockers = blockersFor(rule.id);
    if (rule.modelingStatus === 'unmodeled') {
      blockers.push('unmodeled_rule');
      if (rule.severity !== 'noncritical' || rule.reviewStatus !== 'approved') issue('unmodeled_rule', 'Unmodeled rule requires human noncritical disposition or modeled resolution', rule.id);
    }
    if (rule.reviewStatus === 'auto_approved' && !evaluateApproval({ confidence: rule.confidence, blockers, reviewStatus: rule.reviewStatus }).eligibleForAutoApproval) issue('ineligible_auto_approval', 'Rule cannot be auto-approved', rule.id);
  }
  unique(candidate.registries.map(r=>r.id),'registry entry');
  for(const entry of candidate.registries){
    if(!['approved','auto_approved'].includes(entry.reviewStatus))issue('review_required','Registry entry needs review',entry.id);
    for(const f of [entry.name,...Object.values(entry.attributes)]){
      checkEvidence(factEvidence(f),entry.id);
      if(f.state!=='known'||!approvedFact(f))issue('review_required','Registry fact must be known and approved',entry.id);
      for(const code of factBlockers(f,{required:true,valueType:f.state==='known'?typeof f.value:'string',positiveDimension:false}))issue(code,'Invalid registry fact',entry.id);
      if(f.reviewStatus==='auto_approved'&&f.confidence<.98)issue('ineligible_auto_approval','Registry fact is below approval threshold',entry.id);
    }
    for(const member of entry.productIds){checkEvidence(member.provenance,entry.id);if(!productIds.has(member.value))issue('dangling_registry_member','Registry member is absent from the catalog',entry.id);}
  }
  const benchmark = candidate.benchmark;
  if (!benchmark || benchmark.candidateRevision !== candidate.revision || benchmark.contentHash !== hash || !benchmark.passed || benchmark.truthStatus !== 'human_verified' || !benchmark.productsPass || !benchmark.fieldsPass || !benchmark.rulesPass || !benchmark.footnotesPass || benchmark.scope !== (candidate.coverage.kind === 'subset' ? 'milestone_1' : 'full_document')) issue('benchmark_gate_failed', 'A passing, human-verified benchmark receipt for this exact content and scope is required');
  const validation = candidate.validation;
  if (!validation || validation.candidateRevision !== candidate.revision || validation.contentHash !== hash || !validation.passed) issue('validation_gate_failed', 'A passing validation receipt for this exact content is required');
  return { candidateId: candidate.id, revision: candidate.revision, contentHash: hash, receiptHash: receiptHash(candidate), publishable: !issues.length, issues };
}

/** Pure snapshot builder. A persistence adapter must atomically compare revision/hash and insert once. */
export function preparePublishedSnapshot(raw: unknown, previouslyReviewedGate: PublicationGate, publishedAt: string) {
  z.iso.datetime().parse(publishedAt);
  const candidate = candidateSchema.parse(raw);
  const current = evaluatePublication(candidate);
  if (!current.publishable || !previouslyReviewedGate.publishable || current.candidateId !== previouslyReviewedGate.candidateId || current.revision !== previouslyReviewedGate.revision || current.contentHash !== previouslyReviewedGate.contentHash || current.receiptHash !== previouslyReviewedGate.receiptHash) throw new Error('Publication blocked or gate stale');
  const snapshot = { ...structuredClone(candidate), status: 'published' as const, publishedAt, gate: current };
  function freeze(value: unknown): void {
    if (value && typeof value === 'object') { Object.values(value).forEach(freeze); Object.freeze(value); }
  }
  freeze(snapshot);
  return snapshot;
}
