import {test,expect,vi,afterEach} from 'vitest';
const fake=vi.hoisted(()=>({responses:[] as unknown[],calls:[] as unknown[]}));
vi.mock('openai',()=>({default:class{responses={parse:async(args:unknown)=>{fake.calls.push(args);return {output_parsed:fake.responses.shift(),usage:{input_tokens:10,output_tokens:5}};}};}}));
import {compilePage} from '../../src/ingestion/pipeline';
afterEach(()=>{vi.unstubAllEnvs();fake.responses=[];fake.calls=[];});
const args={page:{pageNumber:1,printedLabel:'I',text:'SYNTHETIC W12. Width 12 inches. Finish Frost only.',blocks:[{text:'SYNTHETIC W12. Width 12 inches. Finish Frost only.',boundingBox:{x:0,y:0,width:1,height:1}}],tables:[]},png:Buffer.from('synthetic-test-image'),provider:'openai',model:'mock-model',documentId:'synthetic-source',documentSha256:'a'.repeat(64),versionId:'synthetic-version',manufacturer:'Synthetic',series:'Synthetic'};
function output(quote='SYNTHETIC W12') {const citation={blockIndices:[0],quote,visualOnly:false};return {products:[{sku:'SYNTHETIC W12',fields:[{name:'sku',value:'SYNTHETIC W12',unknownReason:'',confidence:1,citation}]}],rules:[{id:'finish',sourceText:'Finish Frost only.',citation:{...citation,quote:'Finish Frost only.'},normalizedRuleJson:''}],footnotes:[],warnings:[]};}
function structure(){return {classification:'product_table',confidence:1,regions:[],needsVision:false};}
test('structured provider output becomes unreviewed evidence; unsupported restrictions remain blocking rules',async()=>{vi.stubEnv('OPENAI_API_KEY','synthetic-not-a-real-key');fake.responses=[structure(),output(),{entries:[]},{issues:[],missingSkus:[]}];const result=await compilePage(args);expect(result.records).toHaveLength(2);const product=result.records.find(r=>r.kind==='product');expect(product?.data.reviewStatus).toBe('unreviewed');if(product?.kind==='product')expect(product.data.fields.sku?.confidence).toBe(.97);const rule=result.records.find(r=>r.kind==='rule');if(rule?.kind!=='rule')throw new Error('Rule missing');expect(rule.data.modelingStatus).toBe('unmodeled');expect(result.visionCalls).toBe(0);expect(result.inputTokens).toBe(40);});
test('invented source quotes fail the page instead of becoming approved evidence',async()=>{vi.stubEnv('OPENAI_API_KEY','synthetic-not-a-real-key');fake.responses=[structure(),output('INVENTED SKU')];await expect(compilePage(args)).rejects.toThrow('Source quote does not occur');});
test('missing credentials fail explicitly without a mock production fallback',async()=>{vi.stubEnv('OPENAI_API_KEY','');await expect(compilePage(args)).rejects.toThrow('OPENAI_API_KEY is not configured');expect(fake.calls).toHaveLength(0);});

vi.mock('@anthropic-ai/sdk',()=>({default:class{messages={parse:async(args:unknown)=>{fake.calls.push(args);return {parsed_output:fake.responses.shift(),usage:{input_tokens:10,output_tokens:5}};}};}}));
test('Anthropic adapter uses the same validated extraction contract',async()=>{vi.stubEnv('ANTHROPIC_API_KEY','synthetic-not-a-real-key');fake.responses=[structure(),output(),{entries:[]},{issues:[],missingSkus:[]}];const result=await compilePage({...args,provider:'anthropic'});expect(result.records).toHaveLength(2);expect(result.run.provider).toBe('anthropic');expect(result.inputTokens).toBe(40);});
